In [92]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pylab as plt
plt.style.use('ggplot')
import scipy

<h1> Reading in Data </h1>

In [76]:
players = pd.read_csv('../csv/players.csv')
players.head()

player_id first_name   last_name              name  last_season  \
0        598       Timo  Hildebrand   Timo Hildebrand         2014   
1        670     Martin      Petrov     Martin Petrov         2012   
2       1323     Martin     Amedick    Martin Amedick         2012   
3       3195   Jermaine     Pennant  Jermaine Pennant         2013   
4       3259     Damien        Duff       Damien Duff         2013   

   current_club_id       player_code country_of_birth city_of_birth  \
0               24   timo-hildebrand          Germany         Worms   
1              714     martin-petrov         Bulgaria        Vratsa   
2               24    martin-amedick          Germany     Paderborn   
3              512  jermaine-pennant          England    Nottingham   
4              931       damien-duff          Ireland    Ballyboden   

  country_of_citizenship  ...   foot height_in_cm market_value_in_eur  \
0                Germany  ...    NaN          NaN                 NaN   
1               Bulgaria  ...    NaN          NaN                 NaN   
2                Germany  ...    NaN          NaN                 NaN   
3                England  ...  right        173.0                 NaN   
4                Ireland  ...   left        177.0                 NaN   

  highest_market_value_in_eur  contract_expiration_date  agent_name  \
0                  10000000.0                       NaN         NaN   
1                  12000000.0                       NaN         IFM   
2                   2750000.0                       NaN         NaN   
3                  10500000.0                       NaN  Andrew Sky   
4                  17000000.0                       NaN         NaN   

                                           image_url  \
0  https://img.a.transfermarkt.technology/portrai...   
1  https://img.a.transfermarkt.technology/portrai...   
2  https://img.a.transfermarkt.technology/portrai...   
3  https://img.a.transfermarkt.technology/portrai...   
4  https://img.a.transfermarkt.technology/portrai...   

                                                 url  \
0  https://www.transfermarkt.co.uk/timo-hildebran...   
1  https://www.transfermarkt.co.uk/martin-petrov/...   
2  https://www.transfermarkt.co.uk/martin-amedick...   
3  https://www.transfermarkt.co.uk/jermaine-penna...   
4  https://www.transfermarkt.co.uk/damien-duff/pr...   

  current_club_domestic_competition_id       current_club_name  
0                                   L1     Eintracht Frankfurt  
1                                  ES1  RCD Espanyol Barcelona  
2                                   L1     Eintracht Frankfurt  
3                                  GB1              Stoke City  
4                                  GB1               Fulham FC  

[5 rows x 23 columns]

In [77]:
players.tail()

player_id first_name    last_name                name  last_season  \
30297     371851       Jaka        Bijol          Jaka Bijol         2023   
30298     537171     Semuel  Pizzignacco  Semuel Pizzignacco         2018   
30299     586756      Festy      Ebosele       Festy Ebosele         2023   
30300     704692     Nicolò      Cocetta      Nicolò Cocetta         2022   
30301     925584       Axel     Guessand       Axel Guessand         2023   

       current_club_id         player_code country_of_birth  \
30297              410          jaka-bijol         Slovenia   
30298              410  semuel-pizzignacco            Italy   
30299              410       festy-ebosele          Ireland   
30300              410      nicolo-cocetta            Italy   
30301              410       axel-guessand           France   

                city_of_birth country_of_citizenship  ...   foot height_in_cm  \
30297                Vuzenica               Slovenia  ...  right        190.0   
30298              Monfalcone                  Italy  ...  right        188.0   
30299    Enniscorthy, Wexford                Ireland  ...  right        180.0   
30300  San Daniele del Friuli                  Italy  ...    NaN          NaN   
30301            Schiltigheim                 France  ...   left        184.0   

      market_value_in_eur highest_market_value_in_eur  \
30297          10000000.0                  10000000.0   
30298            325000.0                    350000.0   
30299           4500000.0                   4500000.0   
30300             75000.0                     75000.0   
30301            250000.0                    300000.0   

       contract_expiration_date         agent_name  \
30297       2027-06-30 00:00:00          MSC GROUP   
30298       2025-06-30 00:00:00                NaN   
30299       2027-06-30 00:00:00  The Kulture Group   
30300       2023-06-30 00:00:00                NaN   
30301       2027-06-30 00:00:00        CAA Stellar   

                                               image_url  \
30297  https://img.a.transfermarkt.technology/portrai...   
30298  https://img.a.transfermarkt.technology/portrai...   
30299  https://img.a.transfermarkt.technology/portrai...   
30300  https://img.a.transfermarkt.technology/portrai...   
30301  https://img.a.transfermarkt.technology/portrai...   

                                                     url  \
30297  https://www.transfermarkt.co.uk/jaka-bijol/pro...   
30298  https://www.transfermarkt.co.uk/semuel-pizzign...   
30299  https://www.transfermarkt.co.uk/festy-ebosele/...   
30300  https://www.transfermarkt.co.uk/nicolo-cocetta...   
30301  https://www.transfermarkt.co.uk/axel-guessand/...   

      current_club_domestic_competition_id current_club_name  
30297                                  IT1    Udinese Calcio  
30298                                  IT1    Udinese Calcio  
30299                                  IT1    Udinese Calcio  
30300                                  IT1    Udinese Calcio  
30301                                  IT1    Udinese Calcio  

[5 rows x 23 columns]

In [78]:
players.dtypes

player_id                                 int64
first_name                               object
last_name                                object
name                                     object
last_season                               int64
current_club_id                           int64
player_code                              object
country_of_birth                         object
city_of_birth                            object
country_of_citizenship                   object
date_of_birth                            object
sub_position                             object
position                                 object
foot                                     object
height_in_cm                            float64
market_value_in_eur                     float64
highest_market_value_in_eur             float64
contract_expiration_date                 object
agent_name                               object
image_url                                object
url                                     

In [79]:
players.columns

Index(['player_id', 'first_name', 'last_name', 'name', 'last_season',
       'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'market_value_in_eur',
       'highest_market_value_in_eur', 'contract_expiration_date', 'agent_name',
       'image_url', 'url', 'current_club_domestic_competition_id',
       'current_club_name'],
      dtype='object')

<h3>Let's check how many null values appear and in which columns</h3>

In [80]:
null_counts = players.isnull().sum()
null_counts

player_id                                   0
first_name                               1965
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         2689
city_of_birth                            2203
country_of_citizenship                    543
date_of_birth                              47
sub_position                              172
position                                    0
foot                                     2389
height_in_cm                             2098
market_value_in_eur                     10919
highest_market_value_in_eur              1321
contract_expiration_date                11467
agent_name                              15361
image_url                                   0
url                                         0
current_club_domestic_competition_

In [81]:
players['market_value_in_eur'].fillna(0, inplace=True)
players['highest_market_value_in_eur'].fillna(0, inplace=True)

<h1>Column descriptions</h1>

In [82]:
players.shape

(30302, 23)


<font color='yellow'>player_id:</font> A unique identifier for each player.



<font color='yellow'>first_name:</font> The player's first name. <font color="red">1965 null values.</font> <font color="green">These missing values may be due to lack of information, but we can still rely on the player_id to uniquely identify a player.</font>



<font color='yellow'>last_name:</font> The player's last name.



<font color='yellow'>name:</font> The player's full name.



<font color='yellow'>last_season:</font> The last season in which the player played.



<font color='yellow'>current_club_id:</font> A unique identifier for the player's current club.



<font color='yellow'>player_code:</font> A unique code associated with each player.



<font color='yellow'>country_of_birth:</font> The player's country of birth. <font color="red">2689 null values.</font> <font color="green">These missing values do not represent a problem.</font>



<font color='yellow'>city_of_birth:</font> The player's city of birth. <font color="red">2203 null values.</font> <font color="green">These missing values do not represent a problem.</font>



<font color='yellow'>country_of_citizenship:</font> The player's country of citizenship. <font color="red">543 null values.</font> <font color="green">These missing values do not represent a problem.</font>



<font color='yellow'>date_of_birth:</font> The player's date of birth. <font color="red">47 null values.</font> <font color="green">These missing values do not represent a problem.</font>



<font color='yellow'>position:</font> The player's primary playing position. <font color="red">172 null values.</font> 



<font color='yellow'>sub_position:</font> A secondary position in which the player can play. <font color="green">It should not be a problem. In case of missing values, position can be used.</font>



<font color='yellow'>foot:</font> The player's preferred foot (right, left, etc.). <font color="red">2389 null values.</font> <font color="green">These missing values do not represent a problem.</font>


<font color='yellow'>height_in_cm:</font> The player's height in centimeters. <font color="red">2098 null values.</font> <font color="green">These missing values do not represent a problem.</font>



<font color='yellow'>market_value_in_eur:</font> The player's current market value in euros. <font color="red">10919 null values</font> <font color="green">New or young players often do not have an established market value. Additionally, inactive or retired players may not have a current market value. </font>



<font color='yellow'>highest_market_value_in_eur:</font> The player's highest market value ever reached in euros. <font color="red">1321 null values.</font> <font color="green">This metric, being the historical maximum, is more frequent than the current market value. Even inactive players can have a historical value recorded. </font>



<font color='yellow'>contract_expiration_date:</font> The player's contract expiration date. <font color="red">11437 null values.</font><font color="green">Lack of contract information can be due to players without a contract (free agents), contracts currently being negotiated, or simply outdated data.</font>



<font color='yellow'>agent_name:</font> The player's agent's name. <font color="red">15361 null values</font>  <font color="green">These missing values do not represent a problem.</font>


<font color='yellow'>image_url:</font> An URL to the player's image.



<font color='yellow'>url:</font> An URL to the player's profile on a specific website.



<font color='yellow'>current_club_domestic_competition_id:</font> A unique identifier for the player's current club's domestic competition.



<font color='yellow'>current_club_name:</font> The player's current club's name.



In [83]:
players['height_in_cm'].describe()


count    28204.000000
mean       182.234577
std          6.833916
min         18.000000
25%        178.000000
50%        182.000000
75%        187.000000
max        207.000000
Name: height_in_cm, dtype: float64

<h1> Subsetting Data </h1>

In [84]:
# The columns 'first_name' and 'last_name' were removed, as the player's full name is already available in the column 'name'. The column 'player_code' was removed because 'player_id' provides an equivalent unique identifier. 'current_club_name' was discarded because club information, including the name, can be obtained through 'current_club_id'. Finally, the column 'url' was excluded because it contains only external links, which are not relevant to our analysis.
columns_to_drop = ['first_name', 'last_name', 'player_code', 'current_club_name', 'url']
players_sub = players.drop(columns = columns_to_drop)


<h1> Casting dtypes </h3>

In [85]:
players_sub.dtypes

player_id                                 int64
name                                     object
last_season                               int64
current_club_id                           int64
country_of_birth                         object
city_of_birth                            object
country_of_citizenship                   object
date_of_birth                            object
sub_position                             object
position                                 object
foot                                     object
height_in_cm                            float64
market_value_in_eur                     float64
highest_market_value_in_eur             float64
contract_expiration_date                 object
agent_name                               object
image_url                                object
current_club_domestic_competition_id     object
dtype: object

In [86]:
# The columns 'date_of_birth' and 'contract_expiration_date' were converted to the 'datetime' type.

players_sub['date_of_birth'] = pd.to_datetime(players_sub['date_of_birth'], errors='coerce')

players_sub['contract_expiration_date'] = pd.to_datetime(players_sub['contract_expiration_date'], errors='coerce')

players_sub.dtypes

player_id                                        int64
name                                            object
last_season                                      int64
current_club_id                                  int64
country_of_birth                                object
city_of_birth                                   object
country_of_citizenship                          object
date_of_birth                           datetime64[ns]
sub_position                                    object
position                                        object
foot                                            object
height_in_cm                                   float64
market_value_in_eur                            float64
highest_market_value_in_eur                    float64
contract_expiration_date                datetime64[ns]
agent_name                                      object
image_url                                       object
current_club_domestic_competition_id            object
dtype: obj

<h1> Inspect data </h1>

In [87]:
# checking if player_id column is unique
player_id_unique = players_sub['player_id'].is_unique
player_id_unique

True

In [88]:
# checking if different values for column last_season are correct
players_sub['last_season'].unique()

array([2014, 2012, 2013, 2015, 2017, 2020, 2018, 2019, 2016, 2021, 2022,
       2023], dtype=int64)

<h1> Adding new columns </h1>

In [90]:
# Added an 'is_active' column that indicates whether players are still active, using a criterion where a player is considered active if they have played in at least the last three seasons. The 'market_value_fluctuation' represents the market value change between the highest value reached and the current value. If the current value is zero because the player is no longer active, then the fluctuation will correspond to the highest market value achieved.
current_year = datetime.now().year
years_considered_active = 3
players_sub['is_active'] = (current_year - players_sub['last_season']) <= years_considered_active

players_sub['market_value_fluctuation'] = players_sub['highest_market_value_in_eur'] - players_sub['market_value_in_eur']


players_sub

player_id                name  last_season  current_club_id  \
0            598     Timo Hildebrand         2014               24   
1            670       Martin Petrov         2012              714   
2           1323      Martin Amedick         2012               24   
3           3195    Jermaine Pennant         2013              512   
4           3259         Damien Duff         2013              931   
...          ...                 ...          ...              ...   
30297     371851          Jaka Bijol         2023              410   
30298     537171  Semuel Pizzignacco         2018              410   
30299     586756       Festy Ebosele         2023              410   
30300     704692      Nicolò Cocetta         2022              410   
30301     925584       Axel Guessand         2023              410   

      country_of_birth           city_of_birth country_of_citizenship  \
0              Germany                   Worms                Germany   
1             Bulgaria                  Vratsa               Bulgaria   
2              Germany               Paderborn                Germany   
3              England              Nottingham                England   
4              Ireland              Ballyboden                Ireland   
...                ...                     ...                    ...   
30297         Slovenia                Vuzenica               Slovenia   
30298            Italy              Monfalcone                  Italy   
30299          Ireland    Enniscorthy, Wexford                Ireland   
30300            Italy  San Daniele del Friuli                  Italy   
30301           France            Schiltigheim                 France   

      date_of_birth    sub_position    position   foot  height_in_cm  \
0        1979-04-05      Goalkeeper  Goalkeeper    NaN           NaN   
1        1979-01-15     Left Winger      Attack    NaN           NaN   
2        1982-09-06     Centre-Back    Defender    NaN           NaN   
3        1983-01-15    Right Winger      Attack  right         173.0   
4        1979-03-02  Right Midfield    Midfield   left         177.0   
...             ...             ...         ...    ...           ...   
30297    1999-02-05     Centre-Back    Defender  right         190.0   
30298    2001-09-01      Goalkeeper  Goalkeeper  right         188.0   
30299    2002-08-02  Right Midfield    Midfield  right         180.0   
30300    2003-12-19     Centre-Back    Defender    NaN           NaN   
30301    2004-11-06     Centre-Back    Defender   left         184.0   

       market_value_in_eur  highest_market_value_in_eur  \
0                      0.0                   10000000.0   
1                      0.0                   12000000.0   
2                      0.0                    2750000.0   
3                      0.0                   10500000.0   
4                      0.0                   17000000.0   
...                    ...                          ...   
30297           10000000.0                   10000000.0   
30298             325000.0                     350000.0   
30299            4500000.0                    4500000.0   
30300              75000.0                      75000.0   
30301             250000.0                     300000.0   

      contract_expiration_date         agent_name  \
0                          NaT                NaN   
1                          NaT                IFM   
2                          NaT                NaN   
3                          NaT         Andrew Sky   
4                          NaT                NaN   
...                        ...                ...   
30297               2027-06-30          MSC GROUP   
30298               2025-06-30                NaN   
30299               2027-06-30  The Kulture Group   
30300               2023-06-30                NaN   
30301               2027-06-30        CAA Stellar   

                                               image_url  \
0      https://img

In [94]:
#layers_sub.plot(kind='scatter', x='', y='')
players_sub.plot(kind='scatter', x='player_id', y='date_of_birth', figsize=(10, 6), color='blue')

# Adding title and labels
plt.title('Scatter Plot of Players\' Date of Birth vs Player ID')
plt.xlabel('Player ID')
plt.ylabel('Date of Birth')
plt.show()